---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml

- name: Include firewall tasks
  ansible.builtin.include_tasks: firewall.yml
  when: splunk_network_isolation | default(true)
