---
galaxy_info:
  role_name: common
  namespace: jacobpevans
  author: Jacob Evans
  description: Common configuration for all homelab servers
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
